# Generated by Django 3.1.4 on 2020-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201211_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='shop.Order', verbose_name='Заказы покупателя'),
        ),
    ]
