# Generated by Django 3.1.4 on 2020-12-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20201214_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headphone',
            name='category',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
    ]
